GET http://localhost:5068/teams

###
GET http://localhost:5068/teams/1

###
POST http://localhost:5068/teams
Content-Type: application/json

{
    "name": "Bedouins",
    "division": 1
}

###
PUT http://localhost:5068/teams/1
Content-Type: application/json

{
    "name": "Leicester Foxes",
    "division": 2
}

###
DELETE http://localhost:5068/teams/2